[build]
  # Directory containing the source code
  base = "convoform"
  
  # Command to build your site
  command = "npm run build"
  
  # Directory containing static files to be deployed
  publish = "dist"

# Settings for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Special headers for static assets
[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"